[theme]
base = "dark"
primaryColor = "#00FFAA"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E232E"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
